"""add application_id and unique constraint

Revision ID: d6572c297fe6
Revises: ce842d11ea5a
Create Date: 2025-04-10 15:24:34.408737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6572c297fe6'
down_revision: Union[str, None] = 'ce842d11ea5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('application_id', sa.String(), nullable=True))
    op.create_unique_constraint('uq_company_appid', 'job_applications', ['company_name', 'application_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_company_appid', 'job_applications', type_='unique')
    op.drop_column('job_applications', 'application_id')
    # ### end Alembic commands ###
